### ISSUE TITLE
lower in assertNumeric checks greater or equal

### ISSUE THREAD

**Issue by surmann** [mllg/checkmate#45]
`assertNumeric(0:3, lower = 0)` does not throw an error, although the documentation says "greater than" the value of 'lower'. Is it possible to add an option to check values to be true greater or lower?

**Comment by surmann** [comment]
Done.
Can be solved by `qassert(0:3, "N+(0,)")`.
Thanks!

**Comment by rorynolan** [comment]
The documentation still needs to be fixed for this. Instead of 
* lower Lower value all elements of x must be greater than.
* upper Upper value all elements of x must be lower than.
it should be something like 
* lower Lower value all elements of x must be greater than or equal to.
* upper Upper value all elements of x must be less than or equal to.

**Comment by mllg** [comment]
You are absolutely right. Fixed now.
