### ISSUE TITLE
provide headers to allow linking from C/C++ source

### ISSUE THREAD

**Issue by jackwasey** [mllg/checkmate#46]
Really useful package, but AFAIK the header files need to be in inst/includes in the source so I can link to your package from my C/C++ in my R packages. This would be a helpful addition, and allow people to do good parameter checking in their compiled code without having to write wrapper functions for everything.

**Comment by mllg** [comment]
In principle you're absolutely right, moving the code to inst/includes and allow re-using it in other packages would indeed be a nice addition. OTOH, this is barely documented in the "Writing R extensions" manual. To be more specific, as far as I remember I've only seen this for Rcpp packages and I'm not sure if this approach works for C because it lacks support for namespaces. I personally prefer to check the SEXPs from within R and then rely blindly on the correct input in C/C++.

Would registering some functions as [native routines](http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-to-native-routines-in-other-packages) do the trick for you?

**Comment by jackwasey** [comment]
I don't know enough about the namespace question, but Writing R Extensions says:
"A package that wishes to make use of header files in other packages needs to declare them as a comma-separated list in the field ‘LinkingTo’ in the DESCRIPTION file. This then arranges that the include directories in the installed linked-to packages are added to the include paths for C and C++ code." I would assume that you just include the header and call the function without a namespace, but what do I know?

The native routines thing looks like a possibility, but on a per-function basis, this would be very burdensome for both you and the other package, especially as your package has so many.

Rcpp, using the headers interface, automatically puts header files in inst/include, to be made available for linking. C++ I know, but does add some support for the strategy of putting them there, if this even works for C.

**Comment by mllg** [comment]
> The native routines thing looks like a possibility, but on a per-function basis, this would be very burdensome for both you and the other package, especially as your package has so many.

Totally agree!

> Rcpp, using the headers interface, automatically puts header files in inst/include, to be made available for linking. C++ I know, but does add some support for the strategy of putting them there, if this even works for C.

AFAIK Rcpp copies everything to `inst/include`, not just the header files but also the declarations. If I find some spare time I'll have a closer look how to do this in C.

**Comment by hadley** [comment]
There are some fuller notes at http://r-pkgs.had.co.nz/src.html#clang

**Comment by mllg** [comment]
Thanks Hadley. Two notes on your docs:

```c
void R_init_mypackage(DllInfo *info) {
  R_RegisterCCallable(info, "add_",  (DL_FUNC) &add_)
}
```
First argument to `R_RegisterCCallable` must be the package name as string (`"mypackage"`) and you are missing a `;`.

```c
SEXP add_(SEXP x, SEXP y) {
  static SEXP(fun*)(SEXP, SEXP) = NULL;
  if (fun == NULL)
    fun = (SEXP(*)(SEXP, SEXP)) R_GetCCallable("add", "mypackage");
  return fun(x, y);
}
```
Must be `(*fun)` instead of `(fun*)` in line 2 and the arguments to `R_GetCCallable()` are in reversed order. I can create a PR tomorrow if you want me to.

**Comment by hadley** [comment]
A PR would be awesome!

**Comment by mllg** [comment]
Here is the PR: https://github.com/hadley/r-pkgs/pull/335

I've only registered two functions for now:
```c
Rboolean qtest(SEXP x, const char *rule);
SEXP qassert(SEXP x, const char *rule, const char *name);
```
The interface of `qassert` and `qtest` are pretty convient to use from inside C. Porting the other functions would probably not be beneficial at all because you would have to create plenty of (protected) SEXPs just to pass the arguments down. E.g., `assert_numeric` would have this  signature in C:
```c
SEXP assert_numeric(SEXP x, SEXP lower, SEXP upper, SEXP finite, SEXP any_missing, 
  SEXP all_missing, SEXP len, SEXP min_len, SEXP max_len, SEXP unique, SEXP names);
```
This is just impractical.

Note that registering stuff is still somewhat buggy, the `#ifdef` statements are ignored and thus you may  include `checkmate.h` only once. Same for `xts` and other packages I've looked into.
