### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hmalmedal** [mllg/checkmate#54]
The line

```
assertCharacter(NA, min.chars = 1)
```

gives me a segmentation fault.

**Comment by berndbischl** [comment]
Confirmed. Must be that NA is not of char type, but that operated on with a char command (see min.chars).
I will try to look at it briefly.

**Comment by berndbischl** [comment]
Sorry, I can not fix this exactly now. But I guess it is exactly like I said. in c_check_character one needs  a special case for all_missing / all_missing_atomc.

Do you expect your assert above to pass the assert?
Because an NA does not have chars?

Actually more to the point: 
You should really explicitly set any.na. 
a) So if you set this to FALSE it would mean: Only let pass concrete chars, all which len >= 1. This would 
already work I guess now without a segfault. 
b) Or you really mean any.na = TRUE. This would mean: Either NAs or strings with at least one char. This needs to be fixed and tested. Michel was working on this OR case anyway

**Comment by hmalmedal** [comment]
My use case is

```
assertCharacter(value, min.chars = 1, any.missing = FALSE, len = 1)
```

This crashes when `value` is NA.

**Comment by berndbischl** [comment]
Ok thx for the feedback. Although I guess we need to unit test all cases I outline above.

**Comment by mllg** [comment]
Thanks for the report, it is fixed now. CRAN release is scheduled for next week.
