### ISSUE TITLE
Allow NULL in all assertions

### ISSUE THREAD

**Issue by tdeenes** [mllg/checkmate#70]
It is quite common that one uses NULL as the default for a function argument, and the argument is computed internally in the function unless it is explicitly provided by the user. This means that one has to write the following snippet if using checkmate:
```r
# assume `arg` must be either NULL or a character vector
assert(checkNull(arg), checkCharacter(arg))
```
I would find it convenient to write this instead:
```r
assertCharacter(arg, null = TRUE)
```
In case of an error, I would expect the following message:
```r
# checkCharacter: If not NULL, must be of type 'character', not ...
```

Would you consider adding the `null = FALSE` argument to all assertion functions in the package?

PS: Of course it is pretty easy to write a utility function which transforms a standard `checkSomething` function to a `checkSomethingOrNull` function. Still, I think this addition to the package would be of general interest.

**Comment by berndbischl** [comment]
I have tried to make this argument many times since the creation of the package. 
+1

**Comment by nutterb** [comment]
I nearly made this request once myself, but then decided against it. And I'm not yet persuaded that an `allowNULL` argument is the right thing go do.

The question I would ask is what your function's behavior should be when the argument is NULL? In what circumstances do you use a NULL default without ignoring the argument entirely?  Why isn't 

```r
if (!is.null (arg)) assert (...)
```
Adequate for thsee scenarios.

Given how inexpensive `is.null` is computationall, I suspect this would be more efficient than allowing NULLs in the assertion. But I will need to run some tests to back that up.

I think there needs to be very careful consideration about the side effects of allowing NULL as well. I convinced myself before not to request this, but I can't remember all of my reasoning right now.

**Comment by berndbischl** [comment]
First of all, I am not going to argue about speed here, because all ops are so fast we are talking about, this is really non-topical. What is important is how to write clean, readable, good code.

> Why isn't
> 
> if (!is.null (arg)) assert (...)
> Adequate for thsee scenarios.

@mllg made exactly that argument before. Problem is: This is not entirely realistic and true. 

a) First counter: The error message is now incorrect. Assert will complain that your arg is not, lets say, a numeric. That's misleading as your docs say it can be a numeric or NULL.

b) Second counter: Sometimes you cannot "react" to the fact that "arg" is NULL or not in the same place where you do the arg check. Because it is good practice to handle all the arg checks in the "header" of your function. But often this occurs:

# f(x)
# all my args check, including x  (*1)
# .... 100 lines of other stuff
# finally i can deal with (*2)

so in (*1) and (*2) you now have 2 if (is.null(arg)) calls. And you cannot merge those. We are discussing abstracting away from the first one.

> I think there needs to be very careful consideration about the side effects of allowing NULL as well.

There is no "side-effect"? The point is, your docs say: 
"x can be a numeric or a NULL"

We are talking about a short function that checks that, if you ask for this (the NULL inclusion).
And produces a meaningful error message otherwise.

**Comment by tdeenes** [comment]
I totally agree with @berndbischl. One further note: a possible workaround is to set a zero-length value of the correct type as the default. That is, instead of `myfun(x, extra_arg = NULL)` one can write `myfun(x, extra_arg = character())`. However, this approach has some drawbacks:
1) Sometimes you have a complex argument which can have several types (e.g. can be a single logical flag but also a list or even a function). It is then misleading to provide a specific type which is essentially treated in the internals of the function as a NULL value.
2) Sometimes you expect either NULL or a vector of length N (say N=2). In this scenario you can not write `assertCharacter(extra_arg,  len = 2L)` but should type much more and use `assert(checkCharacter(extra_arg, len = 0L), checkCharacter(extra_arg, len = 2L))`. Not elegant from the developer's point of view and the error message is not so informative for the end user.

**Comment by berndbischl** [comment]
> totally agree with @berndbischl. One further note: a possible workaround is to ... [snip drawbacks]

yes, I agree about the drawbacks. I also dont want arg checks to dictate how I write my signatures. 
In many of my functions I have the case that an arg  needs a value to encode that it is "not there / not given / not specified". I have come to the conclusion that for me, NULL, is the best standard here and has the least drawbacks. Decisions like this should not be influenced by checkmate. If the decisions are reasonable though, cm should support me in implementing them.

**Comment by nutterb** [comment]
I will agree that speed isn't the biggest concern.  Especially when running a function as a one-off.  If you expect your function to be called repeatedly, however (perhaps in a bootstrap, or in an lapply, or in a parallel process), there is potential that loss in speed can compound.  And this can be further compounded if you are making multiple assertions (I have some functions with the potential to run up to 20 assertions).

So to illustrate, I wrote a `checkCharacter_null` function (in my branch of `checkmate`) that has a `null.ok` argument.  I then ran the comparisons below:

```r
library(microbenchmark)
x <- NULL
y <- rep("string", 10000)
microbenchmark(
  check_character_null_value = checkCharacter(NULL),
  check_character2_null_value = checkCharacter_null(NULL),
  check_character2_null_ok = checkCharacter_null(NULL, null.ok = TRUE),
  
  check_character_string = checkCharacter("x"),
  check_character2_string = checkCharacter_null("x"),
  
  check_character_null_in_if = if (!is.null(x)) checkCharacter(x),
  check_character2_null_in_if = if (!is.null(x)) checkCharacter_null(x),
  
  check_character_string_in_if = if (!is.null(y)) checkCharacter(y),
  check_character2_string_in_if = if (!is.null(y)) checkCharacter_null(y)
)

Unit: nanoseconds
                          expr  min   lq    mean median     uq   max neval
    check_character_null_value 3925 4529 5096.26   4830 5132.0 24150   100
   check_character2_null_value 4830 5434 6569.25   5736 6037.5 24451   100
      check_character2_null_ok 2415 3019 3743.88   3020 3322.0 21432   100
        check_character_string 6038 6641 7480.80   6943 7245.0 25960   100
       check_character2_string 6944 7547 9385.55   7548 8151.0 40449   100
    check_character_null_in_if    0    1  360.06    302  303.0 17508   100
   check_character2_null_in_if    0    1  366.05    302  303.0 17509   100
  check_character_string_in_if 6642 7245 9738.76   7246 7849.0 34714   100
 check_character2_string_in_if 7547 7849 9811.17   8151 8453.0 54637   100
```

So while we're talking about nanoseconds for one assertion, nanoseconds still add up over the long term. And it's hard to be the speed of a simple `(if (!is.null))`.


Regarding you first counter-argument (documentation says it may be either `NULL` or `[type]`), I'll concede. I haven't struggled with this much because I generally use an `assertCollection`, which let's me use my own error messages via `coll$push`.  Personally, I don't find this particularly egregious since we are dealing with optional arguments, and the error would only be relevant when the user has actively changed the default from `NULL`.

For your second counter argument, you're right, you can't always deal with the `NULL` around the argument checks.  And you often do have two (or more) `if (is.null)` blocks.  I figure that, at worst, that's an additional 15 characters to type.  By contrast, adding `null.ok = TRUE` will add, at minimum, 10 extra characters if you add the bare minimum `,null.ok=T`.  And while it may be abstracted away, it's still being done.  It's just being done less efficiently for the sake of saving five characters. I don't consider that a worthwhile trade.

All of that being said, if it were incorporated into `checkmate`, it wouldn't really affect me much as I'd just continue to use `if (!is.null)`.  It just feels like a solution without a problem.

**Comment by tdeenes** [comment]
The argumentation about the speed seems a bit biased:
1) You make an unnecessary computation in checkCharacter_null:
`if (null.ok & is.null(x)) return(TRUE)`  should be written as:
`if (null.ok && is.null(x)) return(TRUE)`
This tiny modification leads to this result:
```r
library(microbenchmark)
x <- NULL
y <- rep("string", 10000)
microbenchmark(
    check_character_null_value = checkCharacter(NULL),
    check_character2_null_value = checkCharacter_null(NULL),
    check_character2_null_value2 = checkCharacter_null2(NULL),
    check_character2_null_ok = checkCharacter_null(NULL, null.ok = TRUE),
    check_character2_null_ok2 = checkCharacter_null2(NULL, null.ok = TRUE),
    
    check_character_string = checkCharacter("x"),
    check_character2_string = checkCharacter_null("x"),
    check_character2_string2 = checkCharacter_null2("x"),
    
    check_character_null_in_if = if (!is.null(x)) checkCharacter(x),
    check_character2_null_in_if = if (!is.null(x)) checkCharacter_null(x),
    check_character2_null_in_if2 = if (!is.null(x)) checkCharacter_null2(x),
    
    check_character_string_in_if = if (!is.null(y)) checkCharacter(y),
    check_character2_string_in_if = if (!is.null(y)) checkCharacter_null(y),
    check_character2_string_in_if2 = if (!is.null(y)) checkCharacter_null2(y),
    times = 1000L
)

# Unit: nanoseconds
# expr  min     lq     mean median     uq     max neval    cld
# check_character_null_value 3773 4670.0 5441.922 5066.5 5421.0   25784  1000   c   
# check_character2_null_value 4415 5325.5 6292.499 5722.0 6196.0   38232  1000   c e 
# check_character2_null_value2 3981 4921.0 5979.263 5325.0 5748.5   27739  1000   cd  
# check_character2_null_ok 1569 2010.0 2416.419 2241.5 2543.0   19995  1000  b    
# check_character2_null_ok2 1437 1849.5 2266.649 2068.5 2350.5   14187  1000  b    
# check_character_string 4381 5570.5 6732.349 6018.0 6542.0   42136  1000   c  f
# check_character2_string 4953 6232.5 7463.022 6776.5 7289.5   29310  1000    def
# check_character2_string2 4502 5848.0 8361.403 6276.5 6774.0 1297834  1000      f
# check_character_null_in_if  210  286.5  403.971  328.0  388.0   12846  1000 a     
# check_character2_null_in_if  217  292.0  380.930  330.0  390.0   12386  1000 a     
# check_character2_null_in_if2  208  283.0  390.009  324.0  387.0   13091  1000 a     
# check_character_string_in_if 4701 5922.0 6948.235 6412.0 6864.0   34350  1000   c  f
# check_character2_string_in_if 5439 6533.0 7819.858 7055.0 7615.0   31099  1000     ef
# check_character2_string_in_if2 5100 6208.0 7389.669 6699.5 7185.0   33784  1000    def
```

 2) In the vast majority of the functions I write, the actual computation is much more CPU-expensive (at least by on order of magnitude) than the `checkmate` argument checks (this is one of the major selling point of the `checkmate` package). This means I do not care at all with a +100 nanosecond increase due to the `null.ok` argument.
3) In all my internal functions (or even the exported ones, if necessary), which are expected to be called repeatedly and where argument checks take a non-negligible amount of time, I tend to add an `arg_check = TRUE` argument. This means I do not check the arguments 10000 times because I can check it once before the given function is called.

Of course you are right that the whole `null.ok = FALSE` issue is not something crucial. However, I still think that it would increase my personal wellbeing while using `checkmate`, and based on @berndbischl's comments, I am not alone :). What does @mllg say?

**Comment by nutterb** [comment]
First, good catch for `&` vs `&&`. You're correct that I used the wrong operator. I assure you that it was a matter of clumsiness. Note, however, that even with the correct operator, the null check within the function is still an order of magnitude slower than wrapping the check in `if (!is.null (x))`, which is the more relevant comparison to my addition the the discussion. Namely, that we lose a microsecond of efficiency in each check for the cost of a handful of characters. 

2. An escape from the argument checks is a brilliant idea, and one that I may incorporate into some of my programming.

**Comment by mllg** [comment]
I still think that a `null.ok` argument is not helpful and there are almost always better alternatives. One major advantage of assertions is type-safety which you willingly sacrifice here. Alternatives are

* redesign: is it really necessary for an argument to have multiple types?
* default to empty containers like `character(0)` or `data.frame()`
* default to containers filled with `NA`,  like `c(NA, NA)`
* Use S3 for type juggling

Nevertheless, as this is a somewhat often requested feature, I've implemented it in 17b77eee0c5bd90e8e342f1dd299b79a0e7b655b. Still, I suggest **not** to use it.

**Comment by berndbischl** [comment]
thx for the new feature.

> Nevertheless, as this is a somewhat often requested feature, I've implemented it in 17b77ee. Still, I suggest not to use it.

for completeness:

a bit strange this suggestion, as you are involved in multiple projects where you agreed that "concrete type or NULL" is the best way to handle the case: "param not given". and that after a very lengthy discussion, going through all of the options you listed above, which all didnt work as a standard....

**Comment by tdeenes** [comment]
Although this is not a mind reading game, I think @mllg wanted to emphasize that one should avoid NULL as a viable option for an argument. I agree that NULL should not be used in standard cases, but as @berndbischl states, this is still an acceptable (and maybe the best) way to define "param not given". The other option (not listed above) is to leave it really undefined and use `missing()` in the function body, but I have strong feelings against it. A third option (not listed above) is to call a function which generates the default or tells the function "let's call your default generator function". 

But anyway, thank you for the quick implementation!

**Comment by berndbischl** [comment]
The point is this:

Very often you have this case where you need a special case for "param not given". We all know this. So it is best to have a standard in your package for exactly this case. Mine has become NULL, with very few exceptions. Well, that's my choice, I am not saying it should be everybody's choice. But I would guess that this is a reasonable design choice, and quite a few people have arrived at the same conclusion. 

Why? Because I (and also Michel) have tried every option above. And IMHO they do not work. First of all, saying that one could be "type safe" in this case, is really an illusion. It does not matter whether you use NA, the empty data.frame, or 999 to encode the semantics of this special case. It is still a special case, that need to be handled in code and isnt handled "magically" by the fact that you still have a non-NULL type. So, at least, I would like to have that encoding of that special case to be explicit. 

But, lets go through all of these options:  

> redesign: is it really necessary for an argument to have multiple types?

See my paragraph above. That a special case is needed was our assumption here. And we know that theses unfortunate things go away just because we dont line them. 

> default to empty containers like character(0) or data.frame()

This does not work as the empty container could be a valid value. That alone prohibits this as a standard. Or should I now sometimes use the empty container and sometimes NULL?

> default to containers filled with NA, like c(NA, NA)

See argument above. 

> Use S3 for type juggling

Sure. Lets introduce a type IntegerOrNull. And DataFrameOrNull. I have seen in this in exactly one package before. The result was horrible.

> missing (not in Michel's list but @tdeenes said this)

That's maybe the most "intuitive" thing to use. And I have used this earlier before, it kinda was my "standard" before. But I learned the hard way that this is also a horrible choice. (And the discussion to use something else, NULL, resulted from this horror).

Reasons for missing being bad were twofold. 

a) You cannot actively set an arg to "missing" when you code. So when I use NULL I can do this
```
myarg = ifelse(whatever, NULL, 123)
f(x1, x2, x3, myarg)
```
but with "missing" it now becomes 
```
if (whatever)
  f(x1, x2, x3)
else
  f(x1, x2, x3, myarg = 123)
```

That doesnt look so bad in the example but in reality the call to f() can have very many args. And also just imagine that you would need to do the same thing for x1 and x2. The if-cascade now explodes exponentially.

b) Quite a few very strange bugs exist in R with "missing". E.g. if your arg has the wrong name it won't work and other things. I am sorry, I don't have these cases readily available, but I can distinctively remember that I was (multiple times) left with the choice to either rename args (under an unclear rule system what actually is OK ), or get rid of using "missing". I selected the latter.

Sorry, wall-of-text, but you asked.
